### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x70 and 36x256)

### ISSUE THREAD

**Issue by samin9796** [ming024/FastSpeech2#155]
Hello! I am working on my custom dataset. While running the train.py script, I get the following error:

> Training:   0%|                                      | 0/300000 [00:00<?, ?it/sPrepare training ...                                      | 0/25 [00:00<?, ?it/s]
Number of FastSpeech2 Parameters: 35076161
Removing weight norm...
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    main(args, configs)
  File "train.py", line 96, in main
    output = model(*(batch[2:]))
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/samin/Study/TTS/tts_system/FastSpeech2/model/fastspeech2.py", line 116, in forward
    output = self.encoder(texts, src_masks)
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/samin/Study/TTS/tts_system/FastSpeech2/transformer/Models.py", line 111, in forward
    enc_output = self.src_word_emb(src_seq) + self.position_enc[
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/samin/anaconda3/envs/FastSpeech2/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x70 and 36x256)
Training:   0%|                            | 1/300000 [00:00<8:26:55,  9.86it/s]
Epoch 1:   0%|                                           | 0/25 [00:00<?, ?it/s]

Could you please provide any solution?

**Comment by hadarishav** [comment]
facing the same error. were you able to fix it?
