### ISSUE TITLE
RuntimeError: The size of tensor a (33) must match the size of tensor b (36) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ltydd** [ming024/FastSpeech2#204]
Traceback (most recent call last):                                                                                                                                                 | 1/38 [00:01<01:06,  1.79s/it]
  File "train.py", line 202, in <module>
    main(args, configs)
  File "train.py", line 87, in main
    output = model(*(batch[2:13]))
  File "/home/LtyDD/.conda/envs/fastspeech2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LtyDD/.conda/envs/fastspeech2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/LtyDD/.conda/envs/fastspeech2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LtyDD/Chinese-FastSpeech2/model/fastspeech2.py", line 65, in forward
    output = self.encoder(texts, src_masks, char_vecs=char_vecs)    ##############
  File "/home/LtyDD/.conda/envs/fastspeech2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LtyDD/Chinese-FastSpeech2/transformer/Models.py", line 95, in forward
    enc_output += char_vecs
RuntimeError: The size of tensor a (33) must match the size of tensor b (36) at non-singleton dimension 1
请问有没有人在训练时遇到这个错误？

**Comment by blackbird-fish** [comment]
something wrong with phoneme map,try to reconstruct the map
