### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by WJHBLUESAPPHIRE** [ming024/FastSpeech2#210]
I apply `conda create -n Fastspeech python=3.8` and `pip install -r requirements.txt` and run `python3 preprocess.py config/LJSpeech/preprocess.yaml` and got this error
```
Traceback (most recent call last):
  File "preprocess.py", line 5, in <module>
    from preprocessor.preprocessor import Preprocessor
  File "~/FastSpeech2/preprocessor/preprocessor.py", line 8, in <module>
    import pyworld as pw
  File "/home/wjh/anaconda3/envs/Fastspeech/lib/python3.8/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

my env list is 
```
Package                Version
---------------------- ------------
absl-py                1.4.0
asttokens              2.0.8
audioread              3.0.0
backcall               0.2.0
cachetools             4.2.4
certifi                2023.7.22
cffi                   1.15.1
charset-normalizer     3.2.0
click                  8.1.7
cycler                 0.11.0
Cython                 3.0.2
dataclasses            0.6
debugpy                1.6.3
decorator              5.1.1
Distance               0.1.3
executing              1.1.1
future                 0.18.3
g2p-en                 2.1.0
google-auth            1.35.0
google-auth-oauthlib   0.4.6
grpcio                 1.58.0
idna                   3.4
importlib-metadata     6.8.0
inflect                4.1.0
ipykernel              6.16.0
ipython                8.5.0
jedi                   0.18.1
joblib                 1.3.2
jupyter_client         7.3.5
jupyter-core           4.11.1
kiwisolver             1.4.5
librosa                0.7.2
llvmlite               0.31.0
Markdown               3.4.4
MarkupSafe             2.1.3
matplotlib             3.2.2
matplotlib-inline      0.1.6
nest-asyncio           1.5.6
nltk                   3.8.1
numba                  0.48.0
numpy                  1.19.0
oauthlib               3.2.2
packaging              21.3
parso                  0.8.3
pickleshare            0.7.5
pip                    23.2.1
prompt-toolkit         3.0.31
protobuf               4.24.3
pure-eval              0.2.2
pyasn1                 0.5.0
pyasn1-modules         0.3.0
pycparser              2.21
Pygments               2.13.0
pyparsing              3.1.1
pypinyin               0.39.0
python-dateutil        2.8.2
pyworld                0.2.10
PyYAML                 5.4.1
pyzmq                  24.0.1
regex                  2023.8.8
requests               2.31.0
requests-oauthlib      1.3.1
resampy                0.3.1
rsa                    4.9
scikit-learn           0.23.2
scipy                  1.5.0
setuptools             68.0.0
six                    1.16.0
SoundFile              0.10.3.post1
stack-data             0.5.1
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.1
tgt                    1.4.4
threadpoolctl          3.2.0
torch                  1.7.0
tornado                6.2
tqdm                   4.46.1
traitlets              5.4.0
typing_extensions      4.7.1
Unidecode              1.1.1
urllib3                2.0.4
wcwidth                0.2.5
Werkzeug               2.3.7
wheel                  0.38.4
zipp                   3.16.2
```

**Comment by PussyCat0700** [comment]
I had the same problem with pyworld 0.3.4 but when I downgrade it to pyworld==0.3.0 it works fine.

**Comment by laTH380** [comment]
I faced the same problem but was able to solve it this way.
Thank you.
