### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by bvajk** [ming024/FastSpeech2#236]
All I did was checkout the repo and run `pip3 install -r .\requirements.txt`
I even tried this in a new conda env

the full error is 
```
error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "C:\Users\vajk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\vajk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\vajk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\vajk\AppData\Local\Temp\pip-build-env-vo0sslfr\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\vajk\AppData\Local\Temp\pip-build-env-vo0sslfr\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\vajk\AppData\Local\Temp\pip-build-env-vo0sslfr\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 465, in setup_package
        File "C:\Users\vajk\AppData\Local\Temp\pip-install-f7wqoc2q\numpy_36b8927f5743401e9722af4d96b1a25d\numpy\distutils\core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "C:\Users\vajk\AppData\Local\Temp\pip-install-f7wqoc2q\numpy_36b8927f5743401e9722af4d96b1a25d\numpy\distutils\command\config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "C:\Users\vajk\AppData\Local\Temp\pip-install-f7wqoc2q\numpy_36b8927f5743401e9722af4d96b1a25d\numpy\distutils\mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
```

**Comment by VJJJJJJ1** [comment]
same problem, have you solved it ?

**Comment by JoshRodz027** [comment]
Suddenly got the same issue when trying to install mflflow==2.11.3 within a docker build running "pip install --no-cache-dir -r /py_requirements_delta.txt" in the dockerfile (base image FROM gcr.io/deeplearning-platform-release/tf2-cpu.2-12.py310:m118) . mlflow has a dependency of scipy<2. Poetry tries to compile the versions of scikit-learn available (even though i already have version 1.4.1post1 on my base image) but fails with the same error as @bvajk .

Weirdly, i build another image with a slightly different base image(FROM gcr.io/deeplearning-platform-release/tf2-gpu.2-12.py310:m118) and it worked with no same error (running the same pip install in the dockerfile.

**Comment by aabdumalikov** [comment]
> same problem, have you solved it ?

you have to install numpy's new version
