### ISSUE TITLE
Colab Notebook for Inference

### ISSUE THREAD

**Issue by shoegazerstella** [ming024/FastSpeech2#3]
Hi, thanks for sharing this repo!

I did a Colab Notebook for inference only that you can find here [HERE](https://github.com/shoegazerstella/FastSpeech2/blob/master/FastSpeech2_inference.ipynb).

Even if I have an error when executing the synthesize step

```
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Package cmudict is already up-to-date!
|{F AO1 R AO2 L DH OW1 DH AH0 CH AY0 N IY1 Z T UH1 K IH0 M P R EH1 SH AH0 N Z F R AH1 M W UH1 D B L AA1 K S IH0 N G R EY1 V D IH0 N R IH0 L IY1 F F AO1 R S EH1 N CH ER0 IY0 Z B IH0 F AO1 R DH AH0 W UH1 D K AH2 T ER0 Z AH1 V DH AH0 N EH1 DH ER0 L AH0 N D Z} {B AY1 AH0 S IH1 M AH0 L ER0 P R AA1 S EH2 S}|
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'glow.WaveGlow' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'glow.WN' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:644: SourceChangeWarning: source code of class 'glow.Invertible1x1Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "synthesize.py", line 86, in <module>
    synthesize(model, text, sentence, prefix='step_{}'.format(args.step))
  File "synthesize.py", line 60, in synthesize
    wave_glow = utils.get_WaveGlow()
  File "/content/FastSpeech2/utils.py", line 107, in get_WaveGlow
    wave_glow = wave_glow.remove_weightnorm(wave_glow)
  File "/content/FastSpeech2/glow.py", line 307, in remove_weightnorm
    WN.cond_layers = remove(WN.cond_layers)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 606, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'WN' object has no attribute 'cond_layers'
```

I am still able to generate the speech, but it doesn't sound as it should at all.
[HERE](https://vocaroo.com/3hj01Oi4PnM) the generated speech.

Any idea on what's happening?
Thanks!

**Comment by rishikksh20** [comment]
It just warning, seems model is not well train sounds like griffin Lim quality, it better to use torchhub version on waveglow for simplicity :
```
import torch
waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')
waveglow = waveglow.remove_weightnorm(waveglow)
waveglow = waveglow.to('cuda')
waveglow.eval()
```

**Comment by shoegazerstella** [comment]
Cool! Thank you I'll try that
