### ISSUE TITLE
run  preprocess.py failed with the latest version

### ISSUE THREAD

**Issue by fangg2021** [ming024/FastSpeech2#36]
The TextGrid file at path \preprocessed_data\LJSpeech\TextGrid,and i run preprocess.py. output log like this:

(pytorch_fs02) D:\workspace_tts\FastSpeech2-master>python preprocess.py config/LJSpeech/preprocess.yaml
Processing Data ...
100%|   | 1/1 [00:00<00:00,  1.47it/s]
Computing statistic quantities ...
Traceback (most recent call last):
  File "preprocess.py", line 15, in <module>
    preprocessor.build_from_path()
  File "D:\workspace_tts\FastSpeech2-master\preprocessor\preprocessor.py", line 100, in build_from_path
    pitch_mean = pitch_scaler.mean_[0]
AttributeError: 'StandardScaler' object has no attribute 'mean_'

I need help……

**Comment by fangg2021** [comment]
and scikit-learn pakage version is   0.23.2. If i change the preprocess.yaml's param pitch:normalization=False,it don't have any problems, but the output file is empty

**Comment by fangg2021** [comment]
I get it! the .TextGrid file at the wrong path .I should mkdir a new folder "LJSpeech" in the TextGrid and put the files in.sorry,it's my fault...when i debug to next code ,i have found ...
tg_path = os.path.join(
                    self.out_dir, "TextGrid", speaker, "{}.TextGrid".format(basename)
                )
