### ISSUE TITLE
UnboundLocalError when  running  the preprocessing script

### ISSUE THREAD

**Issue by butaizhang** [ming024/FastSpeech2#87]
Hi, when i tried to run the preprocessing script by  'python3 preprocess.py config/LJSpeech/preprocess.yaml', I got the following error:

Processing Data ...
  0%|                                                                                                                                                                  | 0/218 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "preprocess.py", line 15, in <module>
    preprocessor.build_from_path()
  File "/home/butai/voice/tts/fastspeech2/FastSpeech2-master/preprocessor/preprocessor.py", line 85, in build_from_path
    if len(pitch) > 0:
UnboundLocalError: local variable 'pitch' referenced before assignment

Any idea how to fix this?

 thanks a lot.

**Comment by leminhnguyen** [comment]
Check this issue: https://github.com/ming024/FastSpeech2/issues/64
